export const PLAN_CATALOG = {
  starter: {
    code: 'starter',
    name: 'Starter',
    limits: {
      max_users: 5,
      storage_mb: 2048,
      monthly_uploads: 500,
      monthly_workflows: 200,
      monthly_automations: 150,
      monthly_api_requests: 20000,
      monthly_emails: 3000,
      monthly_signatures: 500,
      monthly_pdf_generation: 1000,
    },
    features: {
      dashboard: true,
      onboarding: true,
      documents: true,
      support: true,
      analytics_advanced: false,
      automation_advanced: false,
      white_label: false,
      ai_assist: false,
      ocr: false,
    },
  },
  professional: {
    code: 'professional',
    name: 'Professional',
    limits: {
      max_users: 20,
      storage_mb: 10240,
      monthly_uploads: 3000,
      monthly_workflows: 1200,
      monthly_automations: 900,
      monthly_api_requests: 120000,
      monthly_emails: 25000,
      monthly_signatures: 6000,
      monthly_pdf_generation: 12000,
    },
    features: {
      dashboard: true,
      onboarding: true,
      documents: true,
      support: true,
      analytics_advanced: true,
      automation_advanced: true,
      white_label: false,
      ai_assist: true,
      ocr: true,
    },
  },
  enterprise: {
    code: 'enterprise',
    name: 'Enterprise',
    limits: {
      max_users: 200,
      storage_mb: 102400,
      monthly_uploads: 50000,
      monthly_workflows: 20000,
      monthly_automations: 15000,
      monthly_api_requests: 2000000,
      monthly_emails: 300000,
      monthly_signatures: 100000,
      monthly_pdf_generation: 200000,
    },
    features: {
      dashboard: true,
      onboarding: true,
      documents: true,
      support: true,
      analytics_advanced: true,
      automation_advanced: true,
      white_label: true,
      ai_assist: true,
      ocr: true,
    },
  },
  whitelabel_future: {
    code: 'whitelabel_future',
    name: 'WhiteLabel (Future)',
    limits: {
      max_users: 500,
      storage_mb: 512000,
      monthly_uploads: 150000,
      monthly_workflows: 50000,
      monthly_automations: 50000,
      monthly_api_requests: 10000000,
      monthly_emails: 1000000,
      monthly_signatures: 500000,
      monthly_pdf_generation: 1000000,
    },
    features: {
      dashboard: true,
      onboarding: true,
      documents: true,
      support: true,
      analytics_advanced: true,
      automation_advanced: true,
      white_label: true,
      ai_assist: true,
      ocr: true,
    },
  },
};

export function getPlan(planCode = 'starter') {
  return PLAN_CATALOG[planCode] || PLAN_CATALOG.starter;
}
