import ProcessosQueueSection from "./ProcessosQueueSection";

export default function ProcessosMaintenanceQueuePanels(props) {
  const monitoringUnsupported = props.monitoringUnsupported;
  const monitoringTone = props.isLightTheme
    ? "border-[#e4d2a8] bg-[#fff8e8] text-[#8a6217]"
    : "border-[#6E5630] bg-[rgba(76,57,26,0.18)] text-[#F8E7B5]";
  const monitoringDashTone = props.isLightTheme
    ? "border-[#e4d2a8] text-[#8a6217]"
    : "border-[#6E5630] text-[#F8E7B5]";

  return (
    <>
      <ProcessosQueueSection queueKey="monitoramento_ativo" title="Monitoramento ativo" eyebrow="Fila paginada" queueTitle="Monitorados" queueHelper="Se a base ainda nao marca monitoramento_ativo, o painel usa fallback pelos processos com account." rows={props.monitoringActive.items} selected={props.selectedMonitoringActive} onToggle={(key) => props.toggleSelection(props.setSelectedMonitoringActive, props.selectedMonitoringActive, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedMonitoringActive, props.selectedMonitoringActive, props.monitoringActive.items, nextState)} page={props.maPage} setPage={props.setMaPage} loading={props.monitoringActive.loading} totalRows={props.monitoringActive.totalRows} pageSize={props.monitoringActive.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "monitoramento_ativo", { monitoringUnsupported })} lastUpdated={props.monitoringActive.updatedAt} limited={props.monitoringActive.limited} errorMessage={props.monitoringActive.error} selectionDisabled={monitoringUnsupported} selectionDisabledMessage={monitoringUnsupported ? "Selecao bloqueada: esta fila serve apenas para diagnosticar a adequacao de schema." : ""} notice={monitoringUnsupported ? <div className={`rounded-[20px] border p-4 text-sm ${monitoringTone}`}>A coluna <strong>monitoramento_ativo</strong> ainda nao existe no HMADV. Esta fila fica em modo diagnostico, com leitura por fallback e sem gravacao.</div> : null} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.monitoramento_ativo} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} />
      <ProcessosQueueSection queueKey="monitoramento_inativo" title="Monitoramento inativo" eyebrow="Fila paginada" queueTitle="Nao monitorados" queueHelper="Use esta fila para reativar o sync dos processos que ficaram fora da rotina." rows={props.monitoringInactive.items} selected={props.selectedMonitoringInactive} onToggle={(key) => props.toggleSelection(props.setSelectedMonitoringInactive, props.selectedMonitoringInactive, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedMonitoringInactive, props.selectedMonitoringInactive, props.monitoringInactive.items, nextState)} page={props.miPage} setPage={props.setMiPage} loading={props.monitoringInactive.loading} totalRows={props.monitoringInactive.totalRows} pageSize={props.monitoringInactive.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "monitoramento_inativo", { monitoringUnsupported })} lastUpdated={props.monitoringInactive.updatedAt} limited={props.monitoringInactive.limited} errorMessage={props.monitoringInactive.error} selectionDisabled={monitoringUnsupported} selectionDisabledMessage={monitoringUnsupported ? "Selecao bloqueada: esta fila mostra somente o backlog dependente da migracao de schema." : ""} notice={monitoringUnsupported ? <div className={`rounded-[20px] border p-4 text-sm ${monitoringTone}`}>Sem a coluna <strong>monitoramento_ativo</strong>, esta fila nao consegue gravar alteracoes. O painel mostra apenas o que precisa de adequacao de schema.</div> : <div className={`rounded-[18px] border border-dashed px-4 py-3 text-xs leading-6 ${monitoringDashTone}`}>Ativar monitoramento marca o processo para sync recorrente e inclui a tag <strong>Datajud</strong> no Freshsales. Desativar remove a tag.</div>} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.monitoramento_inativo} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} />
      <ProcessosQueueSection queueKey="campos_orfaos" title="GAP DataJud -> CRM" eyebrow="Campos orfaos" queueTitle="Campos pendentes no Freshsales" queueHelper="Processos vinculados cujo espelho ainda tem campos importantes em branco." rows={props.fieldGaps.items} selected={props.selectedFieldGaps} onToggle={(key) => props.toggleSelection(props.setSelectedFieldGaps, props.selectedFieldGaps, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedFieldGaps, props.selectedFieldGaps, props.fieldGaps.items, nextState)} page={props.fgPage} setPage={props.setFgPage} loading={props.fieldGaps.loading} totalRows={props.fieldGaps.totalRows} pageSize={props.fieldGaps.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "campos_orfaos")} lastUpdated={props.fieldGaps.updatedAt} limited={props.fieldGaps.limited} errorMessage={props.fieldGaps.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.campos_orfaos} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} />
      <div id="processos-sem-sales-account"><ProcessosQueueSection queueKey="orfaos" title="Sem Sales Account" eyebrow="Processos orfaos" queueTitle="Orfaos" queueHelper="Itens do HMADV que ainda nao viraram Sales Account." rows={props.orphans.items} selected={props.selectedOrphans} onToggle={(key) => props.toggleSelection(props.setSelectedOrphans, props.selectedOrphans, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedOrphans, props.selectedOrphans, props.orphans.items, nextState)} page={props.orphanPage} setPage={props.setOrphanPage} loading={props.orphans.loading} totalRows={props.orphans.totalRows} pageSize={props.orphans.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "orfaos")} lastUpdated={props.orphans.updatedAt} limited={props.orphans.limited} errorMessage={props.orphans.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.orfaos} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} /></div>
    </>
  );
}
