import ProcessosQueueSection from "./ProcessosQueueSection";

export default function ProcessosDataQueuePanels(props) {
  return (
    <>
      <ProcessosQueueSection queueKey="sem_movimentacoes" title="Processos sem movimentacoes" eyebrow="Fila paginada" queueTitle="Sem movimentacoes" queueHelper="Itens sem andamento local para reconsulta no DataJud." rows={props.withoutMovements.items} selected={props.selectedWithoutMovements} onToggle={(key) => props.toggleSelection(props.setSelectedWithoutMovements, props.selectedWithoutMovements, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedWithoutMovements, props.selectedWithoutMovements, props.withoutMovements.items, nextState)} page={props.wmPage} setPage={props.setWmPage} loading={props.withoutMovements.loading} totalRows={props.withoutMovements.totalRows} pageSize={props.withoutMovements.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "sem_movimentacoes")} lastUpdated={props.withoutMovements.updatedAt} limited={props.withoutMovements.limited} errorMessage={props.withoutMovements.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.sem_movimentacoes} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} />
      <div id="processos-movimentacoes-pendentes"><ProcessosQueueSection queueKey="movimentacoes_pendentes" title="Movimentacoes pendentes" eyebrow="Fila paginada" queueTitle="Andamentos sem activity" queueHelper="Processos com movimentacoes no HMADV ainda sem reflexo em sales_activities do Freshsales." rows={props.movementBacklog.items} selected={props.selectedMovementBacklog} onToggle={(key) => props.toggleSelection(props.setSelectedMovementBacklog, props.selectedMovementBacklog, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedMovementBacklog, props.selectedMovementBacklog, props.movementBacklog.items, nextState)} page={props.movPage} setPage={props.setMovPage} loading={props.movementBacklog.loading} totalRows={props.movementBacklog.totalRows} pageSize={props.movementBacklog.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "movimentacoes_pendentes")} lastUpdated={props.movementBacklog.updatedAt} limited={props.movementBacklog.limited} errorMessage={props.movementBacklog.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.movimentacoes_pendentes} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} /></div>
      <div id="processos-publicacoes-pendentes"><ProcessosQueueSection queueKey="publicacoes_pendentes" title="Publicacoes pendentes" eyebrow="Fila paginada" queueTitle="Publicacoes sem activity" queueHelper="Processos com publicacoes no HMADV ainda sem reflexo em sales_activities do Freshsales." rows={props.publicationBacklog.items} selected={props.selectedPublicationBacklog} onToggle={(key) => props.toggleSelection(props.setSelectedPublicationBacklog, props.selectedPublicationBacklog, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedPublicationBacklog, props.selectedPublicationBacklog, props.publicationBacklog.items, nextState)} page={props.pubPage} setPage={props.setPubPage} loading={props.publicationBacklog.loading} totalRows={props.publicationBacklog.totalRows} pageSize={props.publicationBacklog.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "publicacoes_pendentes")} lastUpdated={props.publicationBacklog.updatedAt} limited={props.publicationBacklog.limited} errorMessage={props.publicationBacklog.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.publicacoes_pendentes} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} /></div>
      <div id="processos-partes-sem-contato"><ProcessosQueueSection queueKey="partes_sem_contato" title="Partes sem contato" eyebrow="Fila paginada" queueTitle="Partes a reconciliar" queueHelper="Processos com partes ainda sem contato_freshsales_id, prontos para reconciliacao com o modulo de contatos." rows={props.partesBacklog.items} selected={props.selectedPartesBacklog} onToggle={(key) => props.toggleSelection(props.setSelectedPartesBacklog, props.selectedPartesBacklog, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedPartesBacklog, props.selectedPartesBacklog, props.partesBacklog.items, nextState)} page={props.partesPage} setPage={props.setPartesPage} loading={props.partesBacklog.loading} totalRows={props.partesBacklog.totalRows} pageSize={props.partesBacklog.pageSize} renderStatuses={(row) => props.renderQueueRowStatuses(row, "partes_sem_contato")} lastUpdated={props.partesBacklog.updatedAt} limited={props.partesBacklog.limited} errorMessage={props.partesBacklog.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.partes_sem_contato} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} /></div>
      <ProcessosQueueSection queueKey="audiencias_pendentes" title="Audiencias detectaveis" eyebrow="Fila paginada" queueTitle="Retroativo de audiencias" queueHelper="Processos com sinais concretos de audiencia nas publicacoes e ainda sem persistencia equivalente." rows={props.audienciaCandidates.items} selected={props.selectedAudienciaCandidates} onToggle={(key) => props.toggleSelection(props.setSelectedAudienciaCandidates, props.selectedAudienciaCandidates, key)} onTogglePage={(nextState) => props.togglePageSelection(props.setSelectedAudienciaCandidates, props.selectedAudienciaCandidates, props.audienciaCandidates.items, nextState)} page={props.audPage} setPage={props.setAudPage} loading={props.audienciaCandidates.loading} totalRows={props.audienciaCandidates.totalRows} pageSize={props.audienciaCandidates.pageSize} renderStatuses={(row) => [{ label: `${row.audiencias_pendentes || 0} audiencias pendentes`, tone: "warning" }, row.proxima_data_audiencia ? { label: `proxima ${new Date(row.proxima_data_audiencia).toLocaleDateString("pt-BR")}`, tone: "default" } : null].filter(Boolean)} lastUpdated={props.audienciaCandidates.updatedAt} limited={props.audienciaCandidates.limited} errorMessage={props.audienciaCandidates.error} QueueList={props.QueueList} QueueActionBlock={props.QueueActionBlock} queueConfig={props.queueActionConfigs.audiencias_pendentes} updateQueueBatchSize={props.updateQueueBatchSize} actionState={props.actionState} />
    </>
  );
}
