import { useInternalTheme } from "../../../components/interno/InternalThemeProvider";
import { ViewToggle } from "./ui-primitives";
import { RemoteRunSummary } from "./processos-result-components";
import { CopilotContextCard, SessionSummary } from "./ProcessosHeaderContextCards.js";
import ProcessosHealthSummary from "./ProcessosHealthSummary.js";
import ProcessosPlanSummary from "./ProcessosPlanSummary.js";
import ProcessosReadinessSummary from "./ProcessosReadinessSummary.js";

export default function ProcessosHeaderPanel(props) {
  const { isLightTheme } = useInternalTheme();
  const isResultView = props.view === "resultado";
  return <section className={`rounded-[30px] border px-4 md:px-6 ${isResultView ? "py-4 md:py-5" : "py-5 md:py-6"} ${isLightTheme ? "border-[#d7d4cb] bg-[radial-gradient(circle_at_top_left,rgba(199,155,44,0.12),transparent_35%),linear-gradient(180deg,#fffdf8,#f5f1e8)] text-[#1f2937]" : "border-[#2D2E2E] bg-[radial-gradient(circle_at_top_left,rgba(197,160,89,0.12),transparent_35%),linear-gradient(180deg,rgba(13,15,14,0.98),rgba(8,10,10,0.98))]"}`}><CopilotContextCard copilotContext={props.copilotContext} isLightTheme={isLightTheme} processNumbers={props.processNumbers} /><div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl"><p className={`text-[11px] font-semibold uppercase tracking-[0.2em] ${isLightTheme ? "text-[#9a6d14]" : "text-[#C5A059]"}`}>Centro operacional</p><h3 className="mt-3 font-serif text-4xl leading-tight">Processos com menos ruido, mais decisao e execucao.</h3><p className={`mt-3 max-w-2xl text-sm leading-7 ${isLightTheme ? "text-[#4b5563]" : "opacity-65"}`}>A operacao precisa mostrar o gargalo real, sugerir o melhor lote e reduzir cliques repetidos. O foco agora e decisao clara por etapa, nao um painel monolitico.</p></div><SessionSummary actionState={props.actionState} isLightTheme={isLightTheme} latestHistory={props.latestHistory} selectedSummary={props.selectedSummary} /></div><div className={`mt-6 ${isResultView ? "space-y-3" : "space-y-4"}`}><div className="rounded-[22px] border p-4"><ViewToggle value={props.view} onChange={props.updateView} /><ProcessosHealthSummary backendHealth={props.backendHealth} data={props.data} healthSuggestedActions={props.healthSuggestedActions} isLightTheme={isLightTheme} operationalStatus={props.operationalStatus} trackedQueueErrorCount={props.trackedQueueErrorCount} trackedQueueMismatchCount={props.trackedQueueMismatchCount} />{!isResultView ? <ProcessosPlanSummary getOperationalPlanStepState={props.getOperationalPlanStepState} isLightTheme={isLightTheme} operationalPlan={props.operationalPlan} runOperationalPlanStep={props.runOperationalPlanStep} /> : null}{!isResultView ? <ProcessosReadinessSummary actionState={props.actionState} coverageSchemaExists={props.coverageSchemaExists} coverageSchemaLabel={props.coverageSchemaLabel} handleAction={props.handleAction} isLightTheme={isLightTheme} loadRunnerMetrics={props.loadRunnerMetrics} loadSchemaStatus={props.loadSchemaStatus} runnerAction={props.runnerAction} runnerCoverage={props.runnerCoverage} runnerData={props.runnerData} runnerTagged={props.runnerTagged} /> : null}{!isResultView && props.latestRemoteRun ? <div className="mt-4"><RemoteRunSummary entry={props.latestRemoteRun} /></div> : null}</div></div></section>;
}
