import { useRef, useState } from "react";
import { DEFAULT_QUEUE_BATCHES, EMPTY_FORM } from "./constants";

export function useProcessosPageState() {
  const [view, setView] = useState("operacao");
  const [overview, setOverview] = useState({ loading: true, data: null });
  const [processCoverage, setProcessCoverage] = useState({ loading: true, items: [], totalRows: 0, page: 1, pageSize: 20 });
  const [actionState, setActionState] = useState({ loading: false, error: null, result: null });
  const [executionHistory, setExecutionHistory] = useState([]);
  const [queueRefreshLog, setQueueRefreshLog] = useState([]);
  const [operationalStatus, setOperationalStatus] = useState({ mode: "ok", message: "", updatedAt: null });
  const [backendHealth, setBackendHealth] = useState({ status: "ok", message: "", updatedAt: null });
  const [remoteHistory, setRemoteHistory] = useState([]);
  const [jobs, setJobs] = useState([]);
  const [activeJobId, setActiveJobId] = useState(null);
  const [drainInFlight, setDrainInFlight] = useState(false);
  const [schemaStatus, setSchemaStatus] = useState({ loading: true, data: null });
  const [runnerMetrics, setRunnerMetrics] = useState({ loading: true, data: null });
  const [snapshotAt, setSnapshotAt] = useState(null);
  const [globalError, setGlobalError] = useState(null);
  const [globalErrorUntil, setGlobalErrorUntil] = useState(null);
  const [uiHydrated, setUiHydrated] = useState(false);
  const [pageVisible, setPageVisible] = useState(true);
  const [lastFocusHash, setLastFocusHash] = useState("");
  const bootstrappedRef = useRef(false);
  const snapshotPayloadRef = useRef("");
  const copilotQueryAppliedRef = useRef(false);
  const [limit, setLimit] = useState(2);
  const [queueBatchSizes, setQueueBatchSizes] = useState(DEFAULT_QUEUE_BATCHES);
  const [processNumbers, setProcessNumbers] = useState("");
  const [copilotContext, setCopilotContext] = useState(null);
  const [withoutMovements, setWithoutMovements] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [movementBacklog, setMovementBacklog] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [publicationBacklog, setPublicationBacklog] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [partesBacklog, setPartesBacklog] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [audienciaCandidates, setAudienciaCandidates] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [monitoringActive, setMonitoringActive] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [monitoringInactive, setMonitoringInactive] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [fieldGaps, setFieldGaps] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [orphans, setOrphans] = useState({ loading: true, items: [], updatedAt: null, error: null, errorUntil: null, limited: false });
  const [wmPage, setWmPage] = useState(1), [movPage, setMovPage] = useState(1), [pubPage, setPubPage] = useState(1), [partesPage, setPartesPage] = useState(1), [audPage, setAudPage] = useState(1), [maPage, setMaPage] = useState(1), [miPage, setMiPage] = useState(1), [fgPage, setFgPage] = useState(1), [orphanPage, setOrphanPage] = useState(1), [covPage, setCovPage] = useState(1);
  const [selectedWithoutMovements, setSelectedWithoutMovements] = useState([]), [selectedMovementBacklog, setSelectedMovementBacklog] = useState([]), [selectedPublicationBacklog, setSelectedPublicationBacklog] = useState([]), [selectedPartesBacklog, setSelectedPartesBacklog] = useState([]), [selectedAudienciaCandidates, setSelectedAudienciaCandidates] = useState([]), [selectedMonitoringActive, setSelectedMonitoringActive] = useState([]), [selectedMonitoringInactive, setSelectedMonitoringInactive] = useState([]), [selectedFieldGaps, setSelectedFieldGaps] = useState([]), [selectedOrphans, setSelectedOrphans] = useState([]);
  const [relations, setRelations] = useState({ loading: true, error: null, items: [], totalRows: 0, page: 1, pageSize: 20 });
  const [relationSuggestions, setRelationSuggestions] = useState({ loading: true, error: null, items: [], totalRows: 0, page: 1, pageSize: 20 });
  const [search, setSearch] = useState("");
  const [relationMinScore, setRelationMinScore] = useState("0.45");
  const [lookup, setLookup] = useState({ loading: false, items: [] });
  const [lookupTerm, setLookupTerm] = useState("");
  const [form, setForm] = useState(EMPTY_FORM);
  const [editingRelationId, setEditingRelationId] = useState(null);
  const [selectedRelations, setSelectedRelations] = useState([]);
  const [selectedSuggestionKeys, setSelectedSuggestionKeys] = useState([]);
  const [allMatchingRelationsSelected, setAllMatchingRelationsSelected] = useState(false);
  const [allMatchingSuggestionsSelected, setAllMatchingSuggestionsSelected] = useState(false);
  const [relationSelectionLoading, setRelationSelectionLoading] = useState(false);
  const [suggestionSelectionLoading, setSuggestionSelectionLoading] = useState(false);

  return { actionState, activeJobId, allMatchingRelationsSelected, allMatchingSuggestionsSelected, audPage, audienciaCandidates, backendHealth, bootstrappedRef, copilotContext, copilotQueryAppliedRef, covPage, drainInFlight, editingRelationId, executionHistory, fgPage, fieldGaps, form, globalError, globalErrorUntil, jobs, lastFocusHash, limit, lookup, lookupTerm, maPage, miPage, monitoringActive, monitoringInactive, movPage, movementBacklog, operationalStatus, orphanPage, orphans, overview, pageVisible, partesBacklog, partesPage, processCoverage, processNumbers, pubPage, publicationBacklog, queueBatchSizes, queueRefreshLog, relationMinScore, relationSelectionLoading, relationSuggestions, relations, remoteHistory, runnerMetrics, schemaStatus, search, selectedAudienciaCandidates, selectedFieldGaps, selectedMonitoringActive, selectedMonitoringInactive, selectedMovementBacklog, selectedOrphans, selectedPartesBacklog, selectedPublicationBacklog, selectedRelations, selectedSuggestionKeys, selectedWithoutMovements, setActionState, setActiveJobId, setAllMatchingRelationsSelected, setAllMatchingSuggestionsSelected, setAudPage, setAudienciaCandidates, setBackendHealth, setCopilotContext, setCovPage, setDrainInFlight, setEditingRelationId, setExecutionHistory, setFgPage, setFieldGaps, setForm, setGlobalError, setGlobalErrorUntil, setJobs, setLastFocusHash, setLimit, setLookup, setLookupTerm, setMaPage, setMiPage, setMonitoringActive, setMonitoringInactive, setMovPage, setMovementBacklog, setOperationalStatus, setOrphanPage, setOrphans, setOverview, setPageVisible, setPartesBacklog, setPartesPage, setProcessCoverage, setProcessNumbers, setPubPage, setPublicationBacklog, setQueueBatchSizes, setQueueRefreshLog, setRelationMinScore, setRelationSelectionLoading, setRelationSuggestions, setRelations, setRemoteHistory, setRunnerMetrics, setSchemaStatus, setSearch, setSelectedAudienciaCandidates, setSelectedFieldGaps, setSelectedMonitoringActive, setSelectedMonitoringInactive, setSelectedMovementBacklog, setSelectedOrphans, setSelectedPartesBacklog, setSelectedPublicationBacklog, setSelectedRelations, setSelectedSuggestionKeys, setSelectedWithoutMovements, setSuggestionSelectionLoading, setUiHydrated, setView, setWmPage, snapshotAt, snapshotPayloadRef, suggestionSelectionLoading, uiHydrated, view, wmPage, withoutMovements, setWithoutMovements, setSnapshotAt };
}
