import { useMemo } from "react";

export function useProcessosQueueActionConfigs(args) {
  return useMemo(() => ({
    sem_movimentacoes: { batchSize: args.getQueueBatchSize("sem_movimentacoes"), selectionCount: args.selectedWithoutMovements.length, helper: "Aplica o lote apenas sobre os processos selecionados nesta fila.", actions: [{ label: "Buscar movimentacoes", tone: args.isSuggestedAction("enriquecer_datajud", "buscar_movimentacoes") ? "primary" : "subtle", onClick: () => args.runQueueAction("enriquecer_datajud", "sem_movimentacoes", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.withoutMovements.items, args.selectedWithoutMovements).join("\n")), intent: "buscar_movimentacoes", action: "enriquecer_datajud" }) }] },
    movimentacoes_pendentes: { batchSize: args.getQueueBatchSize("movimentacoes_pendentes"), selectionCount: args.selectedMovementBacklog.length, helper: "Use o lote da fila para refletir apenas os andamentos selecionados no Freshsales.", actions: [{ label: "Sincronizar movimentacoes", tone: args.isSuggestedAction("sincronizar_movimentacoes_activity") ? "primary" : "subtle", onClick: () => args.runQueueAction("sincronizar_movimentacoes_activity", "movimentacoes_pendentes", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.movementBacklog.items, args.selectedMovementBacklog).join("\n")) }) }] },
    publicacoes_pendentes: { batchSize: args.getQueueBatchSize("publicacoes_pendentes"), selectionCount: args.selectedPublicationBacklog.length, helper: "Dispare o lote local para publicar apenas o recorte desta fila.", actions: [{ label: "Sincronizar publicacoes", tone: args.isSuggestedAction("sincronizar_publicacoes_activity") ? "primary" : "subtle", onClick: () => args.runQueueAction("sincronizar_publicacoes_activity", "publicacoes_pendentes", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.publicationBacklog.items, args.selectedPublicationBacklog).join("\n")) }) }] },
    partes_sem_contato: { batchSize: args.getQueueBatchSize("partes_sem_contato"), selectionCount: args.selectedPartesBacklog.length, helper: "O lote atua apenas nas partes dos processos marcados nesta fila.", actions: [{ label: "Reconciliar partes", tone: args.isSuggestedAction("reconciliar_partes_contatos") ? "primary" : "subtle", onClick: () => args.runQueueAction("reconciliar_partes_contatos", "partes_sem_contato", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.partesBacklog.items, args.selectedPartesBacklog).join("\n")) }) }] },
    audiencias_pendentes: { batchSize: args.getQueueBatchSize("audiencias_pendentes"), selectionCount: args.selectedAudienciaCandidates.length, helper: "Retroage audiencias somente para os processos escolhidos nesta fila.", actions: [{ label: "Retroagir audiencias", tone: args.isSuggestedAction("backfill_audiencias") ? "primary" : "subtle", onClick: () => args.runQueueAction("backfill_audiencias", "audiencias_pendentes", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.audienciaCandidates.items, args.selectedAudienciaCandidates).join("\n")), apply: true }) }] },
    monitoramento_ativo: { batchSize: args.getQueueBatchSize("monitoramento_ativo"), selectionCount: args.selectedMonitoringActive.length, helper: args.monitoringUnsupported ? "Fila somente leitura: mostra o backlog que depende da coluna monitoramento_ativo no HMADV." : "Escolha um lote local para sincronizar ou desligar o monitoramento do recorte atual.", actions: args.monitoringUnsupported ? [] : [{ label: "Sincronizar monitorados", tone: args.isSuggestedAction("enriquecer_datajud", "sincronizar_monitorados") ? "primary" : "subtle", onClick: () => args.runQueueAction("enriquecer_datajud", "monitoramento_ativo", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.monitoringActive.items, args.selectedMonitoringActive).join("\n")), intent: "sincronizar_monitorados", action: "enriquecer_datajud" }) }, { label: "Desativar monitoramento", onClick: () => args.runQueueAction("monitoramento_status", "monitoramento_ativo", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.monitoringActive.items, args.selectedMonitoringActive).join("\n")), active: false }) }] },
    monitoramento_inativo: { batchSize: args.getQueueBatchSize("monitoramento_inativo"), selectionCount: args.selectedMonitoringInactive.length, helper: args.monitoringUnsupported ? "Fila somente leitura: o painel mostra apenas o que precisa de adequacao de schema." : "Reative em lote apenas os processos selecionados nesta fila.", actions: args.monitoringUnsupported ? [] : [{ label: "Ativar monitoramento", tone: "primary", onClick: () => args.runQueueAction("monitoramento_status", "monitoramento_inativo", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.monitoringInactive.items, args.selectedMonitoringInactive).join("\n")), active: true }) }] },
    campos_orfaos: { batchSize: args.getQueueBatchSize("campos_orfaos"), selectionCount: args.selectedFieldGaps.length, helper: "Combine reparo de CRM e reenriquecimento apenas para os gaps marcados nesta fila.", actions: [{ label: "Corrigir CRM", tone: args.isSuggestedAction("repair_freshsales_accounts") ? "primary" : "subtle", onClick: () => args.runQueueAction("repair_freshsales_accounts", "campos_orfaos", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.fieldGaps.items, args.selectedFieldGaps).join("\n")) }) }, { label: "Reenriquecer gaps", onClick: () => args.runQueueAction("enriquecer_datajud", "campos_orfaos", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.fieldGaps.items, args.selectedFieldGaps).join("\n")), intent: "reenriquecer_gaps", action: "enriquecer_datajud" }) }] },
    orfaos: { batchSize: args.getQueueBatchSize("orfaos"), selectionCount: args.selectedOrphans.length, helper: "Cria Sales Accounts apenas para os processos escolhidos nesta fila.", actions: [{ label: "Criar accounts", tone: args.isSuggestedAction("push_orfaos") ? "primary" : "subtle", onClick: () => args.runQueueAction("push_orfaos", "orfaos", { processNumbers: args.resolveActionProcessNumbers(args.getSelectedNumbers(args.orphans.items, args.selectedOrphans).join("\n")) }) }] },
  }), [args]);
}
