import { CONTACT_TYPE_OPTIONS } from "./constants";
import { HealthBadge } from "./ui-primitives";

export function PublicacaoDetailPanel({
  detailState,
  detailEditForm,
  setDetailEditForm,
  detailLinkType,
  setDetailLinkType,
  selectedPendingParteIds,
  selectedLinkedParteIds,
  onTogglePendingParte,
  onToggleLinkedParte,
  onTogglePendingPage,
  onToggleLinkedPage,
  onLinkPendingPartes,
  onMoveLinkedPartes,
  onReclassifyLinkedPartes,
  onUnlinkLinkedPartes,
  onRefresh,
  onSaveContact,
  onApplyValidation,
  actionLoading,
  validationLabel,
  validationTone,
  formatValidationMeta,
  formatDateTimeLabel,
}) {
  const row = detailState?.row || null;
  const data = detailState?.data || null;
  const linkedItems = data?.linkedPartes?.items || [];
  const pendingItems = data?.pendingPartes?.items || [];
  const firstLinkedContact = linkedItems.find((item) => item?.contact?.freshsales_contact_id)?.contact || data?.contactDetail?.contact || null;
  const allPendingSelected = pendingItems.length > 0 && pendingItems.every((item) => selectedPendingParteIds.includes(item.id));
  const allLinkedSelected = linkedItems.length > 0 && linkedItems.every((item) => selectedLinkedParteIds.includes(item.id));

  return (
    <div className="space-y-4">
      {!row ? <p className="text-sm opacity-60">Selecione um item da lista para abrir o detalhe integrado.</p> : null}
      {row ? <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold break-all">{row.numero_cnj}</p><HealthBadge label={row.queueSource} tone={row.queueSource === "partes" ? "warning" : "default"} /><HealthBadge label={validationLabel(row.validation?.status)} tone={validationTone(row.validation?.status)} /></div>{row.titulo ? <p className="mt-2 text-sm opacity-75">{row.titulo}</p> : null}{formatValidationMeta(row.validation) ? <p className="mt-2 text-xs opacity-55">Ultima validacao: {formatValidationMeta(row.validation)}</p> : null}<div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={onRefresh} className="border border-[#2D2E2E] px-3 py-2 text-xs hover:border-[#C5A059] hover:text-[#C5A059]">Recarregar detalhe</button><button type="button" onClick={() => onApplyValidation("validado")} className="border border-[#30543A] px-3 py-2 text-xs text-[#B7F7C6]">Validar</button><button type="button" onClick={() => onApplyValidation("revisar")} className="border border-[#6E5630] px-3 py-2 text-xs text-[#FDE68A]">Marcar revisar</button><button type="button" onClick={() => onApplyValidation("bloqueado")} className="border border-[#5B2D2D] px-3 py-2 text-xs text-[#FECACA]">Bloquear</button></div></div> : null}
      {detailState.loading ? <p className="text-sm opacity-60">Carregando detalhe integrado...</p> : null}
      {detailState.error ? <p className="text-sm text-red-300">{detailState.error}</p> : null}
      {data?.coverage?.totalRows > 0 && !data?.coverage?.items?.length ? <div className="border border-[#6E5630] bg-[rgba(76,57,26,0.18)] p-4 text-sm text-[#FDE68A]"><p className="font-semibold">Cobertura parcial do processo</p><p className="mt-2 opacity-90">O processo foi encontrado na contagem, mas os detalhes nao vieram completos nesta leitura. Recarregue o detalhe para uma nova tentativa.</p></div> : null}
      {data?.coverage?.items?.[0] ? <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><p className="font-semibold">Processo relacionado na base</p><div className="mt-2 flex flex-wrap gap-x-4 gap-y-1 text-xs opacity-65"><span>CNJ: {data.coverage.items[0].numero_cnj || row?.numero_cnj}</span>{data.coverage.items[0].account_id_freshsales ? <span>Conta: {data.coverage.items[0].account_id_freshsales}</span> : null}{data.coverage.items[0].status_atual_processo ? <span>Status: {data.coverage.items[0].status_atual_processo}</span> : null}</div>{data.coverage.items[0].titulo ? <p className="mt-2 opacity-70">{data.coverage.items[0].titulo}</p> : null}</div> : null}
      {(data?.linkedPartes?.limited || data?.pendingPartes?.limited) ? <div className="border border-[#6E5630] bg-[rgba(76,57,26,0.18)] p-4 text-sm text-[#FDE68A]"><p className="font-semibold">Partes carregadas em modo reduzido</p><p className="mt-2 opacity-90">A listagem de partes pode estar parcial nesta leitura. Use "Recarregar detalhe" antes de editar em lote se precisar de garantia total.</p></div> : null}
      <div className="grid gap-4 md:grid-cols-2">
        <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Partes vinculadas</p><p className="mt-1 text-xs opacity-60">{linkedItems.length} carregada(s)</p></div><button type="button" onClick={() => onToggleLinkedPage(!allLinkedSelected)} disabled={!linkedItems.length} className="border border-[#2D2E2E] px-3 py-2 text-xs hover:border-[#C5A059] hover:text-[#C5A059] disabled:opacity-40">{allLinkedSelected ? "Desmarcar lista" : "Selecionar lista"}</button></div><div className="mt-3 space-y-2">{linkedItems.slice(0, 8).map((item) => <label key={item.id} className="block border border-[#2D2E2E] p-3 cursor-pointer"><div className="flex gap-3"><input type="checkbox" checked={selectedLinkedParteIds.includes(item.id)} onChange={() => onToggleLinkedParte(item.id)} className="mt-1" /><div className="min-w-0 flex-1"><p className="font-semibold">{item.nome}</p><p className="mt-1 text-xs opacity-60">{item.tipo_contato || "sem tipo"} {item.contact?.name ? `• ${item.contact.name}` : ""}</p></div></div></label>)}{!linkedItems.length ? <p className="text-xs opacity-60">Nenhuma parte vinculada carregada.</p> : null}</div></div>
        <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Partes pendentes</p><p className="mt-1 text-xs opacity-60">{pendingItems.length} carregada(s)</p></div><button type="button" onClick={() => onTogglePendingPage(!allPendingSelected)} disabled={!pendingItems.length} className="border border-[#2D2E2E] px-3 py-2 text-xs hover:border-[#C5A059] hover:text-[#C5A059] disabled:opacity-40">{allPendingSelected ? "Desmarcar lista" : "Selecionar lista"}</button></div><div className="mt-3 space-y-2">{pendingItems.slice(0, 8).map((item) => <label key={item.id} className="block border border-[#2D2E2E] p-3 cursor-pointer"><div className="flex gap-3"><input type="checkbox" checked={selectedPendingParteIds.includes(item.id)} onChange={() => onTogglePendingParte(item.id)} className="mt-1" /><div className="min-w-0 flex-1"><p className="font-semibold">{item.nome}</p><p className="mt-1 text-xs opacity-60">{item.polo || "sem polo"} {item.tipo_pessoa ? `• ${item.tipo_pessoa}` : ""}</p></div></div></label>)}{!pendingItems.length ? <p className="text-xs opacity-60">Nenhuma parte pendente carregada.</p> : null}</div></div>
      </div>
      {(linkedItems.length || pendingItems.length) ? <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><div className="grid gap-3 md:grid-cols-[240px_auto_auto_auto_auto]"><label className="text-xs uppercase tracking-[0.14em] opacity-60">Tipo alvo<select value={detailLinkType} onChange={(event) => setDetailLinkType(event.target.value)} className="mt-2 w-full border border-[#2D2E2E] bg-[#050706] px-3 py-2 text-sm text-[#F4F1EA]">{CONTACT_TYPE_OPTIONS.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><button type="button" onClick={onLinkPendingPartes} disabled={actionLoading || !selectedPendingParteIds.length || !firstLinkedContact?.freshsales_contact_id} className="self-end border border-[#2D2E2E] px-3 py-2 text-xs hover:border-[#C5A059] hover:text-[#C5A059] disabled:opacity-40">Vincular pendentes</button><button type="button" onClick={onMoveLinkedPartes} disabled={actionLoading || !selectedLinkedParteIds.length || !firstLinkedContact?.freshsales_contact_id} className="self-end border border-[#2D2E2E] px-3 py-2 text-xs hover:border-[#C5A059] hover:text-[#C5A059] disabled:opacity-40">Mover vinculadas</button><button type="button" onClick={onReclassifyLinkedPartes} disabled={actionLoading || !selectedLinkedParteIds.length} className="self-end border border-[#6E5630] px-3 py-2 text-xs text-[#F8E7B5] disabled:opacity-40">Reclassificar</button><button type="button" onClick={onUnlinkLinkedPartes} disabled={actionLoading || !selectedLinkedParteIds.length} className="self-end border border-[#5B2D2D] px-3 py-2 text-xs text-[#FECACA] disabled:opacity-40">Desvincular</button></div><div className="mt-3 flex flex-wrap gap-3 text-xs opacity-65"><span>Pendentes marcadas: {selectedPendingParteIds.length}</span><span>Vinculadas marcadas: {selectedLinkedParteIds.length}</span><span>Tipo alvo: {detailLinkType}</span></div></div> : null}
      {data?.validationHistory?.length ? <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Historico de validacao</p><p className="text-xs opacity-60">Ultimas alteracoes registradas para este CNJ.</p></div><HealthBadge label={`${data.validationHistory.length} evento(s)`} tone="default" /></div><div className="mt-4 space-y-3">{data.validationHistory.map((entry) => <div key={entry.id} className="border border-[#2D2E2E] p-3"><div className="flex flex-wrap items-center gap-2"><HealthBadge label={validationLabel(entry.status)} tone={validationTone(entry.status)} />{entry.updatedBy ? <span className="text-xs opacity-60">{entry.updatedBy}</span> : null}{entry.createdAt ? <span className="text-xs opacity-50">{formatDateTimeLabel(entry.createdAt)}</span> : null}</div>{entry.note ? <p className="mt-2 opacity-75">{entry.note}</p> : null}</div>)}</div></div> : null}
      {firstLinkedContact ? <div className="border border-[#2D2E2E] bg-[rgba(13,15,14,0.96)] p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-semibold">Contato integrado</p><p className="text-xs opacity-60">{firstLinkedContact.freshsales_contact_id || data?.contactDetail?.contact?.freshsales_contact_id}</p></div>{firstLinkedContact.freshsales_url ? <a href={firstLinkedContact.freshsales_url} target="_blank" rel="noreferrer" className="text-xs underline hover:text-[#C5A059]">Abrir no CRM</a> : null}</div><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs uppercase tracking-[0.14em] opacity-60">Nome<input value={detailEditForm.name} onChange={(event) => setDetailEditForm((state) => ({ ...state, name: event.target.value }))} className="mt-2 w-full border border-[#2D2E2E] bg-transparent px-3 py-2 text-sm text-[#F4F1EA]" /></label><label className="text-xs uppercase tracking-[0.14em] opacity-60">Email<input value={detailEditForm.email} onChange={(event) => setDetailEditForm((state) => ({ ...state, email: event.target.value }))} className="mt-2 w-full border border-[#2D2E2E] bg-transparent px-3 py-2 text-sm text-[#F4F1EA]" /></label><label className="text-xs uppercase tracking-[0.14em] opacity-60">Telefone<input value={detailEditForm.phone} onChange={(event) => setDetailEditForm((state) => ({ ...state, phone: event.target.value }))} className="mt-2 w-full border border-[#2D2E2E] bg-transparent px-3 py-2 text-sm text-[#F4F1EA]" /></label><label className="text-xs uppercase tracking-[0.14em] opacity-60">Observacao operacional<input value={detailEditForm.note} onChange={(event) => setDetailEditForm((state) => ({ ...state, note: event.target.value }))} className="mt-2 w-full border border-[#2D2E2E] bg-transparent px-3 py-2 text-sm text-[#F4F1EA]" /></label></div><div className="mt-3"><button type="button" onClick={onSaveContact} disabled={actionLoading} className="bg-[#C5A059] px-4 py-2 text-xs font-semibold uppercase tracking-[0.15em] text-[#050706] disabled:opacity-50">Salvar contato</button></div></div> : null}
    </div>
  );
}
