export const EVENT_REGISTRY = {
  // Mandatory sprint 0.7 events
  'onboarding.started': { domain: 'onboarding', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'onboarding.completed': { domain: 'onboarding', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'onboarding.document.uploaded': { domain: 'onboarding', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'onboarding.approved': { domain: 'onboarding', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'document.uploaded': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.approved': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.rejected': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.signature.requested': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.signed': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'debt.created': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'debt.updated': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'debt.overdue': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'minimum.existential.updated': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'financial.score.changed': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'plan.generated': { domain: 'plans', owner: 'plans', version: '1.0.0', tenantAware: true },
  'plan.approved': { domain: 'plans', owner: 'plans', version: '1.0.0', tenantAware: true },
  'plan.recalculated': { domain: 'plans', owner: 'plans', version: '1.0.0', tenantAware: true },
  'notification.created': { domain: 'notifications', owner: 'notifications', version: '1.0.0', tenantAware: true },
  'notification.read': { domain: 'notifications', owner: 'notifications', version: '1.0.0', tenantAware: true },
  'token.generated': { domain: 'security', owner: 'security', version: '1.0.0', tenantAware: true },
  'login.failed': { domain: 'security', owner: 'security', version: '1.0.0', tenantAware: true },
  'suspicious.activity.detected': { domain: 'security', owner: 'security', version: '1.0.0', tenantAware: true },
  'subscription.created': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'subscription.updated': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'quota.exceeded': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'storage.limit.reached': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'feature.enabled': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'feature.disabled': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'invoice.generated': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'payment.received': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'payment.failed': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'invoice.failed': { domain: 'billing', owner: 'billing', version: '1.0.0', tenantAware: true },
  'workflow.failed': { domain: 'workflows', owner: 'platform', version: '1.0.0', tenantAware: true },
  'onboarding.abandoned': { domain: 'onboarding', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'ai.workflow.started': { domain: 'ai', owner: 'platform', version: '1.0.0', tenantAware: true },
  'integration.requested': { domain: 'integrations', owner: 'platform', version: '1.0.0', tenantAware: true },
  'integration.completed': { domain: 'integrations', owner: 'platform', version: '1.0.0', tenantAware: true },
  'integration.failed': { domain: 'integrations', owner: 'platform', version: '1.0.0', tenantAware: true },
  'integration.webhook.received': { domain: 'integrations', owner: 'platform', version: '1.0.0', tenantAware: true },
  'integration.webhook.failed': { domain: 'integrations', owner: 'platform', version: '1.0.0', tenantAware: true },

  // Existing app events kept for backward compatibility
  'journey.step.state_changed': { domain: 'journey', owner: 'journey', version: '1.0.0', tenantAware: true },
  'journey.step.completed': { domain: 'journey', owner: 'journey', version: '1.0.0', tenantAware: true },
  'video.ready': { domain: 'media', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'video.progress': { domain: 'media', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'video.completed': { domain: 'media', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'video.error': { domain: 'media', owner: 'onboarding', version: '1.0.0', tenantAware: true },
  'debt.loaded': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'debt.list.changed': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'debt.deleted': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
  'document.list.changed': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.created': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'document.updated': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'upload.started': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'upload.completed': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'upload.failed': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'upload.validation_error': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'signature.requested': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'signature.completed': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'signature.resent': { domain: 'documents', owner: 'documents', version: '1.0.0', tenantAware: true },
  'tenant.ready': { domain: 'tenant', owner: 'shell', version: '1.0.0', tenantAware: true },
  'auth.ready': { domain: 'auth', owner: 'shell', version: '1.0.0', tenantAware: true },
  'auth.unauthenticated': { domain: 'auth', owner: 'shell', version: '1.0.0', tenantAware: true },
  'auth.changed': { domain: 'auth', owner: 'shell', version: '1.0.0', tenantAware: true },
  'auth.error': { domain: 'auth', owner: 'shell', version: '1.0.0', tenantAware: true },
  'shell.ready': { domain: 'shell', owner: 'shell', version: '1.0.0', tenantAware: true },
  'modal.opened': { domain: 'shell', owner: 'shell', version: '1.0.0', tenantAware: true },
  'modal.closed': { domain: 'shell', owner: 'shell', version: '1.0.0', tenantAware: true },
  'slideover.opened': { domain: 'shell', owner: 'shell', version: '1.0.0', tenantAware: true },
  'slideover.closed': { domain: 'shell', owner: 'shell', version: '1.0.0', tenantAware: true },
  'financial.saved': { domain: 'financial', owner: 'financial', version: '1.0.0', tenantAware: true },
};

export function getEventDefinition(eventName) {
  return EVENT_REGISTRY[eventName] || null;
}

export function listRegisteredEvents() {
  return Object.keys(EVENT_REGISTRY);
}
